create table if not exists public.room_slots (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  room_slug text not null,
  room_name text not null,
  slot_date date not null,
  start_time time not null,
  end_time time not null,
  capacity integer not null default 1,
  price_2 numeric(12,2) not null default 340,
  price_3 numeric(12,2) not null default 495,
  price_4 numeric(12,2) not null default 640,
  price_5 numeric(12,2) not null default 775,
  price_6 numeric(12,2) not null default 900,
  price_7 numeric(12,2) not null default 1120,
  price_8 numeric(12,2) not null default 1280,
  is_blocked boolean not null default false,
  block_reason text,
  notes text
);

create unique index if not exists room_slots_unique_slot_idx
on public.room_slots (room_slug, slot_date, start_time, end_time);

create index if not exists room_slots_room_date_idx
on public.room_slots (room_slug, slot_date, start_time);

create or replace function public.set_room_slots_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_room_slots_updated_at on public.room_slots;
create trigger trg_room_slots_updated_at
before update on public.room_slots
for each row
execute function public.set_room_slots_updated_at();
