create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  first_name text,
  last_name text,
  full_name text,
  email text,

  phone_home text,
  phone_work text,
  phone_mobile text,
  primary_phone text,

  address_1 text,
  address_2 text,
  city text,
  state_province text,
  zip_postcode text,
  country text,

  gender text,
  date_of_birth date,
  external_created_at date,

  total_bookings integer not null default 0,
  cancellations integer not null default 0,
  no_shows integer not null default 0,
  mailing_list boolean not null default false,
  credit numeric(12,2) not null default 0,

  membership_enrolled text,
  member_until date,
  membership_rate text,
  membership_paused_from date,
  membership_paused_until date,
  membership_next_payment date,

  last_visit date,
  next_visit date,
  alert_message text,
  require_approval boolean not null default false,

  language text not null default 'ar',
  rooms jsonb not null default '[]'::jsonb,
  status text not null default 'win' check (status in ('win', 'lose', 'champion')),
  is_champion boolean not null default false,
  video_requested boolean not null default false,
  video_sent boolean not null default false
);

create index if not exists customers_email_idx on public.customers (email);
create index if not exists customers_primary_phone_idx on public.customers (primary_phone);
create index if not exists customers_last_visit_idx on public.customers (last_visit desc);
create index if not exists customers_external_created_at_idx on public.customers (external_created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_customers_updated_at on public.customers;
create trigger trg_customers_updated_at
before update on public.customers
for each row
execute function public.set_updated_at();
